language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "node_modules"
install:
  - npm install -g vuepress@1.2.0
script:
  - vuepress build docs

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
