os: linux
language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "node_modules"
install:
  - npm install -g vuepress@1.2.0
script:
  - vuepress build docs

deploy:
  provider: pages
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
